// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHVJ4m5tfFd3rx9iNFt8Rk0dDk5DPp108',
    appId: '1:282734580073:web:2d524d7b2d9457ff6c6df8',
    messagingSenderId: '282734580073',
    projectId: 'doctor-appointments-c3e30',
    authDomain: 'doctor-appointments-c3e30.firebaseapp.com',
    storageBucket: 'doctor-appointments-c3e30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Tan3OKtIHMF86nS_9r0IZcd-IqNzcjU',
    appId: '1:282734580073:android:92f5d1062d1c26e46c6df8',
    messagingSenderId: '282734580073',
    projectId: 'doctor-appointments-c3e30',
    storageBucket: 'doctor-appointments-c3e30.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHVJ4m5tfFd3rx9iNFt8Rk0dDk5DPp108',
    appId: '1:282734580073:web:a6de6e7f63c1259e6c6df8',
    messagingSenderId: '282734580073',
    projectId: 'doctor-appointments-c3e30',
    authDomain: 'doctor-appointments-c3e30.firebaseapp.com',
    storageBucket: 'doctor-appointments-c3e30.firebasestorage.app',
  );
}
